name: 'ReFlex Shared Types: Build'
description: 'Install NPM packages and build shared types'

runs:
  using: 'composite'

jobs:
  build-shared-types:
    runs-on: windows-latest
    name: build shared ts types
    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@main
      - name: setup node and install packages
        uses: ./.github/actions/npm-install
      - name: build shared types
        run: npm run build:shared-types
